version: '3'

services:
  sdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
    ports:
      - "3309:3306"
  sapi:
    build: 
      context: ./backend/project/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
  sweb:
    build: 
      context: ./frontend/app/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

# 이미지 삭제 스크립트 실행
volumes:
  cleanup:
    external: true
  scripts:
    driver: local
    name: "${PWD}/scripts"
  image_cleanup:
    image: alpine:latest
    entrypoint: ["/bin/sh", "-c"]
    command: ["cp /scripts/cleanup.sh /target && /target/cleanup.sh"]
    volumes:
      - cleanup:/scripts
      - scripts:/target
    depends_on:
      - sdb
      - sapi
      - sweb
