version: '3'

services:
  noblyapi:
    container_name: noblyapi
    build:
      context: ./backend/project
      dockerfile: Dockerfile
    image: noblyapiimg
    ports:
      - "8080:8080"
    networks:
      - noblynet

  noblyweb:
    container_name: noblyweb
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    image: noblywebimg
    volumes:
      - /home/ubuntu/nobly/fileserver/videos:/app/videos
    ports:
      - "3000:3000"
    networks:
      - noblynet

  noblyfileserver:
    container_name: noblyfileserver
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    image: noblyfileserverimg
    volumes:
      - /home/ubuntu/nobly/fileserver/videos:/usr/share/nginx/html
    ports:
      - "8880:80"
    networks:
      - noblynet

networks:
  noblynet:
